### ISSUE TITLE
Hierarchical Inference paper for January 28, 2020

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/BreakfastClub#1]
@makagan Want to propose a good starter paper for our first meeting, 0900 PST on 1/28/2020? Sebastian @swagnercarena has agreed to be our first lead reader :-) Others, feel free to chime in as well.

**Comment by makagan** [comment]
Hi All, I think we discussed reading:

Hierarchical Implicit Models and Likelihood-Free Variational Inference
by Dustin Tran, Rajesh Ranganath, David M. Blei

https://arxiv.org/abs/1702.08896

Is this reasonable, or would you prefer to start with a paper on more traditional Hierarchical inference?

**Comment by drphilmarshall** [comment]
I think this is a good one - and it has the basic math of hierarchical Bayes in it, I notice. @swagnercarena tells me that he is up for it, so I'll assign this issue to him, and look forward to hearing his discussion of it on Tues Jan 28! Thanks @makagan , thanks Sebastian!
